services:
  nginx:
    image: nginx:1.27-alpine
    container_name: back-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - php84
    networks:
      - back-net

  php84:
    build:
      context: ./docker/php/8.4
      dockerfile: Dockerfile
    container_name: back-php84
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      TZ: UTC
    networks:
      - back-net

  php85:
    build:
      context: ./docker/php/8.5
      dockerfile: Dockerfile
    container_name: back-php85
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      TZ: UTC
    networks:
      - back-net
    profiles:
      - php85 # ⛔ پیش‌فرض اجرا نمی‌شود

  mysql:
    image: mysql:8.4
    container_name: back-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hihesab
      MYSQL_USER: hossein
      MYSQL_PASSWORD: hossein
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back-net

  # redis:
  #   image: redis:7-alpine
  #   container_name: back-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - back-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: back-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - back-net

networks:
  back-net:
    driver: bridge

volumes:
  mysql-data:
